apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: handyshare/payment-service:latest
        imagePullPolicy: Always  # This ensures it pulls the latest image
        ports:
        - containerPort: 8084
        envFrom:
        - secretRef:
            name: payment-service-secrets