apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - protocol: TCP
      port: 5151           # Service's internal port (cluster-internal endpoint)
      targetPort: 3306     # Port on the pod where MySQL is listening
  selector:
    app: mysql             # Routes to pods with this label
  type: ClusterIP          # Makes service accessible from outside the cluster