apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW5kZXZlbG9wZXJz # admindevelopers - this is the password for the user with root privileges 
  MYSQL_USER: YWRtaW4= #admin
  MYSQL_PASSWORD: amFydmlzMDA3 #jarvis007
  MYSQL_DATABASE: ZGVtbw== #demo