# k8s/user-auth/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-auth-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:5151/auth"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admindevelopers"
  JWT_SECRET: "e7b03c0c0329ed5a8bbac042d38c6d93f7344516ac51203552476cf58f07b62c"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "2431049737-jqqkl0607p9b98qaqgsoc1rug4e3nvpv.apps.googleusercontent.com"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "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"