apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-deployment
  template:
    metadata:
      labels:
        app: reviews-deployment
    spec:
      containers:
      - name: reviews-deployment
        image: handyshare/reviews:latest
        imagePullPolicy: Always  # This ensures it pulls the latest image
        ports:
        - containerPort: 8089
        envFrom:
        - secretRef:
            name: reviews-deployment-secrets