export const frontendRoutes = {
  EXAMPLE: "#",
  HOME: "/",
  DASHBOARD: "/dashboard",
  SERVICE: "/services",
  PORTFOLIO: "/portfolio",
  LOGIN: "/login",
  REGISTER: "/register",
  ADD_AVAIBILITY: "/add-availability",
  BOOKING: "/booking",
  PROVIDER_DASHBOARD: "/dashboard2",
  REGISTER_SERVICE: "/register-service",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PAYMENT: "/payment",
};
